#!/usr/bin/env bash
# Write a Bash script that transfers a file from our client to a server

if [ ARGV < 4 ]
then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
    scp -o StrictHostKeyChecking=no ARVG[1] ARVG[2] ARVG[3] ARVG[4]
fi
