#!/usr/bin/env bash
#Configure your Nginx server so that /redirect_me is redirecting to another page.

STRING="Hello World!"
REDIRECT="\n\tlocation /redirect_me {\n\t\treturn 301 https://youtu.be/dQw4w9WgXcQ; \n\t}\n"
FILE="/etc/nginx/sites-available/default"
sudo apt-get -y update
sudo apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "$STRING" > /var/www/html/index.nginx-debian.html
sed -i "37i\ $REDIRECT" "$FILE"
sudo service nginx restart
