#!/usr/bin/env bash
# change port

sudo chmod 777 /etc/nginx/sites-enabled/default
sudo sed -i "s/listen 8080 default_server;/listen 80 default_server;/;" /etc/nginx/sites-enabled/default
sudo sed -i "s/8080 default_server ipv6only=on;/80 default_server ipv6only=on;/" /etc/nginx/sites-enabled/default
sudo service nginx start
