#!/usr/bin/env bash
#Fix the container user to Nginx as the nginx user

sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
sed -i "s/80 default_server/8080 default_server/" /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
pkill apache2
sudo -u nginx service nginx restart
